---
- name: Install node and npm
  become: true
  hosts: ubuntu_server
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new linux user for node app
  hosts: ubuntu_server
  become: true
  vars_files:
    - deploy_node_vars.yaml
  tasks:
    - name: Create linux user
      user:
        name: "{{linux_name}}"
        comment: node admin user
        group: osboxes

- name: Deploy nodejs app
  hosts: ubuntu_server
  become: true
  become_user: "{{linux_name}}"
  vars_files:
    - deploy_node_vars.yaml
  tasks:
    - name: Unpack the nodejs tar file
      unarchive:
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{user_home_dir}}"
    - name: Install dependencies
      npm:
        path: "{{user_home_dir}}/package/"
    - name: Start the application
      command:
        chdir: "{{user_home_dir}}/package/app/"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep "node server"
      register: app_status
    - debug: msg={{app_status.stdout_lines}}

